### PR TITLE
AbstractBufferredRollingFileAppender: Rework the flush and sync logic when the appender is closed (fixes #19).

### LINKED ISSUE #19: AbstractBufferedRollingFileAppender doesn't shut down the background threads on close causing the JVM not to exit
### Bug

When the appender is closed, at least one of the background threads in `AbstractBufferedRollingFileAppender` continues to run, and since they aren't daemon threads, they prevent the JVM from shutting down. This happens regardless of whether `closeFileOnFlush` is set.

### log4j1-appenders version

0.2.0

### Environment

* Java 11
* Ubuntu 20.04

### Reproduction steps

* Write an appender that is derived from `AbstractBufferedRollingFileAppender`
* Use the appender in an application
* The application will not exit unless killed

### PR DESCRIPTION
**Pull request by kirkrodrigues**
# References

#19

# Description

There were several issues with the flush & sync logic on close:
* The background threads weren't daemons.
* The `BackgroundFlushThread` was never interrupted, so it continued running even when `closeFileOnShutdown` was true.
* Several parts of the code treated `InterruptedException` as if it would be received when the JVM was shutting down, but that's not true.

This PR solves the issues:
* The threads are now daemons. When `closeFileOnShutdown` is true and the JVM is shutting down, the threads will continue flushing & syncing logs since daemon threads continue to run during the execution of shutdown hooks.
* They are interrupted as necessary.
* Erroneous uses of InterruptedException are removed.
* New unit tests added to test the flush & sync logic when the appender is closed.

# Validation performed

Validated new and old unit tests passed

### CODE REVIEW

File: src/main/java/com/yscope/logging/log4j1/AbstractBufferedRollingFileAppender.java [hunk 1]
```diff
@@ -62,37 +65,62 @@
...
-  private final BackgroundFlushThread backgroundFlushThread = new BackgroundFlushThread();
-  private final BackgroundSyncThread backgroundSyncThread = new BackgroundSyncThread();
+  private final Thread backgroundFlushThread = new Thread(new BackgroundFlushRunnable());
+  private final BackgroundSyncRunnable backgroundSyncRunnable = new BackgroundSyncRunnable();
+  private final Thread backgroundSyncThread = new Thread(backgroundSyncRunnable);
+  private final Thread shutdownHookThread = new Thread(new ShutdownHookRunnable());
+  private volatile boolean closeWithDelayedShutdown = false;
 
-  private long numEventsLogged = 0L;
+  private volatile long numEventsLogged = 0L;
```
Comment (jackluo923) [inline src/main/java/com/yscope/logging/log4j1/AbstractBufferedRollingFileAppender.java:118]: Can we switch to atomic long because volatile doesn't guarantee thread safety for increment.

File: src/test/java/com/yscope/logging/log4j1/TestRollingFileLogAppender.java [hunk 2]
```diff
@@ -292,34 +436,39 @@ private void validateNumSyncAndCloseEvents (RollingFileTestAppender appender, in
...
+        "FATAL=" + flushFatalLevelTimeout + ",ERROR=" + flushErrorLevelTimeout + ",INFO="
+            + flushInfoLevelTimeout;
     appender.setFlushHardTimeoutsInMinutes(disableHardTimeout ? disabledTimeoutCsv : timeoutCsv);
     appender.setFlushSoftTimeoutsInSeconds(disableSoftTimeout ? disabledTimeoutCsv : timeoutCsv);
 
-    appender.activateOptions();
     return appender;
   }
+
+  private void triggerContextSwitch () {
```
Comment (jackluo923) [inline src/test/java/com/yscope/logging/log4j1/TestRollingFileLogAppender.java]: Improve the documentation of why we need to trigger context switch, i.e unit test runs in single thread.

**Review by jackluo923 — CHANGES_REQUESTED** [review]

**Review by jackluo923 — APPROVED** [review]

**Review by jackluo923 — APPROVED** [review]
